stages:
  - unit-test
  - build
  - component-test

unit-test:
  image: node:10-alpine
  stage: unit-test
  script:
    - apk add --update python make g++
    - npm i npm@latest -g
    - npm ci
    - npm run test
  coverage:
    '/Statements.*?(\d+(?:\.\d+)?)%/'

build:
  image: node:10-alpine
  stage: build
  script:
    - apk add --update python make g++
    - npm i npm@latest -g
    - npm ci
    - npm run build

component-test:
  image: cypress/base:10
  stage: component-test
  script:
    - npm i npm@latest -g
    - npm ci
    - npx gatsby build
    - npx gatsby serve & npx wait-on http://localhost:9000
    - npx cypress run
  artifacts:
    paths:
      - cypress/videos
      - cypress/screenshots
    expire_in: 1 day
