image: node:lts-alpine

stages:
  - test
  - build

test:
  stage: test
  script:
    - npm i npm@latest -g
    - npm i
    - npm run test
  coverage:
    '/Statements.*?(\d+(?:\.\d+)?)%/'

build:
  stage: build
  script:
  - npm i npm@latest -g
  - npm i
  - npm run build
